export const Products = [
  {
    id: 1,
    name: "Cap",
    image: require("../Components/assests/img1.jpg").default,
    price: 3500,
    instock: 8,
    fastDelivery: true,
    rating: 4,
  },
  {
    id: 2,
    name: "Red Shoe",
    image: require("../Components/assests/img2.jpg").default,
    price: 13000,
    instock: 2,
    fastDelivery: true,
    rating: 5,
  },
  {
    id: 3,
    name: "WristWatch",
    image: require("../Components/assests/img3.jpg").default,
    price: 11000,
    instock: 4,
    fastDelivery: false,
    rating: 5,
  },
  {
    id: 4,
    name: "Suit",
    image: require("../Components/assests/img4.jpg").default,
    price: 22000,
    instock: 11,
    fastDelivery: true,
    rating: 3,
  },
  {
    id: 5,
    name: "blue shoe",
    image: require("../Components/assests/img5.jpg").default,
    price: 15000,
    instock: 2,
    fastDelivery: true,
    rating: 3,
  },
  {
    id: 6,
    name: "Lady red dress",
    image: require("../Components/assests/img6.jpg").default,
    price: 5500,
    instock: 12,
    fastDelivery: false,
    rating: 3,
  },
  {
    id: 7,
    name: "White cap",
    image: require("../Components/assests/img7.jpg").default,
    price: 300,
    instock: 12,
    fastDelivery: true,
    rating: 2,
  },
  {
    id: 8,
    name: "Lady intalia",
    image: require("../Components/assests/img8.jpg").default,
    price: 11000,
    instock: 6,
    fastDelivery: false,
    rating: 5,
  },
  {
    id: 9,
    name: "Lion Art",
    image: require("../Components/assests/img9.jpg").default,
    price: 12000,
    instock: 1,
    fastDelivery: false,
    rating: 4,
  },
  {
    id: 10,
    name: "GOW",
    image: require("../Components/assests/img10.jpg").default,
    price: 22500,
    instock: 5,
    fastDelivery: true,
    rating: 5,
  },
  {
    id: 11,
    name: "Chenrby",
    image: require("../Components/assests/img11.jpg").default,
    price: 3500,
    instock: 8,
    fastDelivery: true,
    rating: 2,
  },
  {
    id: 12,
    name: "StarWars",
    image: require("../Components/assests/img12.jpg").default,
    price: 5000,
    instock: 18,
    fastDelivery: false,
    rating: 4,
  },
];
